/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppStatementsRouteImport } from './routes/app.statements'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSecurityRouteImport } from './routes/app.security'
import { Route as AppReconcileRouteImport } from './routes/app.reconcile'
import { Route as AppReadinessRouteImport } from './routes/app.readiness'
import { Route as AppPortalRouteImport } from './routes/app.portal'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppBookkeepingRouteImport } from './routes/app.bookkeeping'
import { Route as AppAuditsRouteImport } from './routes/app.audits'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppReconcileRoute = AppReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => AppRoute,
} as any)
const AppReadinessRoute = AppReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppBookkeepingRoute = AppBookkeepingRouteImport.update({
  id: '/bookkeeping',
  path: '/bookkeeping',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsRoute = AppAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/audits': typeof AppAuditsRoute
  '/app/bookkeeping': typeof AppBookkeepingRoute
  '/app/crm': typeof AppCrmRoute
  '/app/portal': typeof AppPortalRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/reconcile': typeof AppReconcileRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/audits': typeof AppAuditsRoute
  '/app/bookkeeping': typeof AppBookkeepingRoute
  '/app/crm': typeof AppCrmRoute
  '/app/portal': typeof AppPortalRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/reconcile': typeof AppReconcileRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/audits': typeof AppAuditsRoute
  '/app/bookkeeping': typeof AppBookkeepingRoute
  '/app/crm': typeof AppCrmRoute
  '/app/portal': typeof AppPortalRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/reconcile': typeof AppReconcileRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/portal'
    | '/privacy'
    | '/terms'
    | '/app/audits'
    | '/app/bookkeeping'
    | '/app/crm'
    | '/app/portal'
    | '/app/readiness'
    | '/app/reconcile'
    | '/app/security'
    | '/app/settings'
    | '/app/statements'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/privacy'
    | '/terms'
    | '/app/audits'
    | '/app/bookkeeping'
    | '/app/crm'
    | '/app/portal'
    | '/app/readiness'
    | '/app/reconcile'
    | '/app/security'
    | '/app/settings'
    | '/app/statements'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/portal'
    | '/privacy'
    | '/terms'
    | '/app/audits'
    | '/app/bookkeeping'
    | '/app/crm'
    | '/app/portal'
    | '/app/readiness'
    | '/app/reconcile'
    | '/app/security'
    | '/app/settings'
    | '/app/statements'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/statements': {
      id: '/app/statements'
      path: '/statements'
      fullPath: '/app/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reconcile': {
      id: '/app/reconcile'
      path: '/reconcile'
      fullPath: '/app/reconcile'
      preLoaderRoute: typeof AppReconcileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/readiness': {
      id: '/app/readiness'
      path: '/readiness'
      fullPath: '/app/readiness'
      preLoaderRoute: typeof AppReadinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portal': {
      id: '/app/portal'
      path: '/portal'
      fullPath: '/app/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookkeeping': {
      id: '/app/bookkeeping'
      path: '/bookkeeping'
      fullPath: '/app/bookkeeping'
      preLoaderRoute: typeof AppBookkeepingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audits': {
      id: '/app/audits'
      path: '/audits'
      fullPath: '/app/audits'
      preLoaderRoute: typeof AppAuditsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditsRoute: typeof AppAuditsRoute
  AppBookkeepingRoute: typeof AppBookkeepingRoute
  AppCrmRoute: typeof AppCrmRoute
  AppPortalRoute: typeof AppPortalRoute
  AppReadinessRoute: typeof AppReadinessRoute
  AppReconcileRoute: typeof AppReconcileRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditsRoute: AppAuditsRoute,
  AppBookkeepingRoute: AppBookkeepingRoute,
  AppCrmRoute: AppCrmRoute,
  AppPortalRoute: AppPortalRoute,
  AppReadinessRoute: AppReadinessRoute,
  AppReconcileRoute: AppReconcileRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
